#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""Docstring
matrix to s2p-file and s2p-file to matrix utils
Authors: Jose Vicente Martínez Sánchez de Rojas, Juan Del Pino Mena 
"""


def mat2file(mat, path, device_idn):
    """
    Write matrix into a s2p-file
    :param mat: matrix 
    :param path: path to file, including its name. .s2p extension is automatically added

    mat format:
    Npoints rows
    9 cols: f[Hz], s11(mag,pha)[dB], s21 (mag,pha)[dB], s12(mag,pha)[dB], s22(mag,pha)[dB]
    """

    with open(path, 'w+') as f:

        f.write("!" + IDN + '\n')
        f.write("!File generated by LCAF-GAM-UPV software\n")
        f.write("!josevmart@iteam.upv.es ; jdelpin@iteam.upv.es\n")
        f.write("!S2P File: Measurements: S11, S21, S12, S22:\n")
        f.write("# Hz S  dB   R 50\n")

        for i in range (len(Mat)): #TO-DO? dynamic length

            line = str(int(Mat[i][0]))

            for j in range (8):
                line = line + ' {0:2.6e}'.format(Mat[i][j+1])
                
            f.write(line + '\n')



def file2mat(path):
    """
    Read s2p-file and load it into a matrix
    :param path: path to file, including its name. .s2p extension is automatically added

    mat format:
    Npoints rows
    9 cols: f[Hz], s11(mag,pha)[dB], s21 (mag,pha)[dB], s12(mag,pha)[dB], s22(mag,pha)[dB]
    """

    mat = []

    with open(path, 'r') as f:

        for line in f:

            if line != '\n' and line[0] != '#' and line[0] != '!':

                strvalues = line.split()
                values = []
                values.append(float(strvalues[0]))

                for j in range (8):
                    values.append(float(strvalues[j+1]))

                mat.append(values)

    return mat
    
                
