#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""Docstring
matrix to s2p-file and s2p-file to matrix utils
Authors: Juan Del Pino Mena, Jose Vicente Martínez Sánchez de Rojas
"""


def mat2file(mat, path, device_idn):
    """
    Write matrix into a s2p-file
    :param mat: matrix 
    :param path: path to file, including its name. .s2p extension is automatically added

    mat format:
    Npoints rows
    9 cols: f[Hz], s11(mag,pha)[dB], s21 (mag,pha)[dB], s12(mag,pha)[dB], s22(mag,pha)[dB]
    """

    with open(path, 'w+', encoding="utf-8") as f:

        f.write(f"!{device_idn}\n")
        f.write("!File generated by LCAF-GAM-iTEAM-UPV software\n")
        f.write("!jdelpin@iteam.upv.es ; josevmart@iteam.upv.es\n")
        f.write("!S2P File: Measurements: S11, S21, S12, S22:\n")
        f.write("# Hz S  dB   R 50\n")

        for line in mat:
            f.write(" ".join((f"{num:2.6e}" for num in line)) + "\n")


def file2mat(path):
    """
    Read s2p-file and load it into a matrix
    :param path: path to file, including its name. .s2p extension is automatically added

    mat format:
    n_points rows
    9 cols: f[Hz], s11(mag,pha)[dB], s21 (mag,pha)[dB], s12(mag,pha)[dB], s22(mag,pha)[dB]
    """

    mat = []

    with open(path, 'r', encoding="utf-8") as f:

        for line in f:
            if line != '\n' and line[0] != '#' and line[0] != '!':

                strvalues = line.split()
                values = []
                values.append(float(strvalues[0]))

                for j in range (8):
                    values.append(float(strvalues[j+1]))

                mat.append(values)

    return mat
